// import axios from "axios";

export async function getLaboratories() {
  // const response = await axios.get("url");
  // return response.data;
  return [
    {
      id: 1,
      name: "Laboratório Central",
      cnpj: "12.345.678/0001-90",
      cep: "01001-000",
      responsible: "João da Silva",
      address: "Rua Fulano de Tal, 456",
      city: "São Paulo",
      uf: "SP",
      phone: "(11) 91234-5678",
      email: "central@labs.com.br",
      avatar: null,
      status: { id: 1, color: "#24b92b", description: "Ativo" },
      coordinates: "teste",
    },
    {
      id: 2,
      name: "Laboratório Norte",
      cnpj: "98.765.432/0001-11",
      cep: "22040-020",
      responsible: "Maria Oliveira",
      address: "Av. Atlântica, 1200",
      city: "Rio de Janeiro",
      uf: "RJ",
      phone: "(21) 99876-5432",
      email: "norte@labs.com.br",
      avatar: null,
      status: { id: 2, color: "#fd2a2a", description: "Inativo" },
      coordinates: "teste",
    },
    {
      id: 3,
      name: "Laboratório Minas",
      cnpj: "45.678.912/0001-55",
      cep: "30130-010",
      responsible: "Carlos Pereira",
      address: "Rua das Acácias, 90",
      city: "Belo Horizonte",
      uf: "MG",
      phone: "(31) 93456-7890",
      email: "minas@labs.com.br",
      avatar: null,
      status: { id: 1, color: "#24b92b", description: "Ativo" },
      coordinates: "teste",
    },
    {
      id: 4,
      name: "Laboratório Sul",
      cnpj: "11.222.333/0001-44",
      cep: "90010-150",
      responsible: "Fernanda Costa",
      address: "Rua dos Andradas, 800",
      city: "Porto Alegre",
      uf: "RS",
      phone: "(51) 91234-0000",
      email: "sul@labs.com.br",
      avatar: null,
      status: { id: 1, color: "#24b92b", description: "Ativo" },
      coordinates: "teste",
    },
    {
      id: 5,
      name: "Laboratório Nordeste",
      cnpj: "66.777.888/0001-22",
      cep: "40020-000",
      responsible: "Rafael Santos",
      address: "Av. Sete de Setembro, 250",
      city: "Salvador",
      uf: "BA",
      phone: "(71) 99888-7766",
      email: "nordeste@labs.com.br",
      avatar: null,
      status: { id: 2, color: "#fd2a2a", description: "Inativo" },
      coordinates: "teste",
    },
    {
      id: 6,
      name: "Laboratório Centro-Oeste",
      cnpj: "33.444.555/0001-99",
      cep: "70040-010",
      responsible: "Lucas Almeida",
      address: "Eixo Monumental, Bloco B",
      city: "Brasília",
      uf: "DF",
      phone: "(61) 95555-3333",
      email: "centrooeste@labs.com.br",
      avatar: null,
      status: { id: 1, color: "#24b92b", description: "Ativo" },
      coordinates: "teste",
    },
  ];
}
